[build-system]
requires = ["maturin>=1.0,<2.0", "polars>=1.3.0"]
build-backend = "maturin"

[project]
name = "pl-col-collapse"
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = [
    "maturin>=1.9.3",
    "polars<=1.32.1",
]

[tool.maturin]
module-name = "pl_col_collapse._internal"

[dependency-groups]
dev = [
    "mimesis>=18.0.0",
    "pytest>=8.3.5",
    "pytest-cov",
    "pytest-randomly>=3.16.0",
]
